spring.application.name=plantoks


### DATABASE CONFIG ###

spring.datasource.url=jdbc:postgresql://localhost/plantoks
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.show_sql=true
spring.jpa.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
### END DATABASE CONFIG ###

### GRAPHQL CONFIG ###
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

# GraphQL endpoint
spring.graphql.path=/graphql

# Schema locations (add this)
spring.graphql.schema.locations=classpath:graphql/

### END GRAPHQL CONFIG ###